# Generated by Django 4.0.5 on 2022-06-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
