# Generated by Django 4.0.5 on 2022-06-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_comment_body_alter_comment_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
